# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQHYFQBJoWFQiwB5RKSzuRpX_sbItq_g
"""

import pandas as pd
df=pd.DataFrame ({'Ism':[ 'Jvohir', 'Nurillo','Muhhammadsher','Muhammadrizo', 'SHohjahon','Omadbek','Tolibjon','Shokirjon','Boynazar','Sardorbek'],
                 'Familya': ['Abduqodirov','Aminjonov','Inomov','Isoqjonov','Janobiddinov','Rasulov','Rayimjonov','Sobidov','Toxtasinov','Soliyev'],
                 'Yoshi':[ '19', '19', '19', '19', '19', '19','19','19', '19', '20'],
                 'Kursi': ['2','2', '2', '4','3', '3', '2',  '2', '3', '2' ]
                 })
print(df)





